import tkinter as tk
from PIL import ImageTk, Image

win = tk.Tk()
win.title("Department View")
win.geometry("600x600")
img = Image.open(r"C:\Users\Ali\PycharmProjects\PoliceDepartment\resources\a.png")
img = img.resize((600, 630))
img = ImageTk.PhotoImage(img)
tk.Label(master=win,image=img).pack(fill=tk.BOTH,expand=True)
tk.Label(win,text="Name",font="arial 15 bold").place(x=30,y=50)
tk.Entry(win,font="arial 10",bd=3).place(x=100,y=55)
tk.Label(win,text="Family",font="arial 15 bold").place(x=20,y=110)
tk.Entry(win,font="arial 10",bd=3).place(x=100,y=110)
tk.Label(win,text="Employee Number",font="arial 15 bold").place(x=20,y=170)
tk.Entry(win,font="arial 12",bd=3).place(x=220,y=170)
tk.Label(win,text="Check In Shift",font="arial 15 bold").place(x=20,y=230)
tk.Checkbutton(win,background="black").place(x=170,y=230)
tk.Label(win,text="Shift Location",font="arial 15 bold").place(x=20,y=290)
tk.Entry(win,font="arial 10",bd=3).place(x=170,y=295)
tk.Button(win,text="Exit",font="arial 15 bold",command=win.quit).place(x=500,y=500)
win.mainloop()